In [1]:
text = '''Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country's partnership with India among the "most consequential in the world". The BBC's Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit's potential in strengthening the ties between the two nations.

The US's relationship with India - the world's most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.

The remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.

A key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China's growing influence in the Indo-Pacific. India-US ties had not lived up to their promise following a landmark civilian nuclear deal in 2005 because a liability law passed by India three years later hobbled purchase of reactors.

"This followed a fading commitment to the relationship during [former prime minister] Manmohan Singh's second term as the leader of a coalition government. With Mr Modi there has been a lot more enthusiasm about embracing the US. Mr Biden has also given an overall broad directive to make it work," says Seema Sirohi, author of Friends With Benefits: The India-US Story.

Ms Sirohi says the US put in a "lot of effort to make Mr Modi's visit substantive and have a lot of deliverables". Defence-industrial cooperation and technology topped the list. Consider this:

General Electric and India's state-owned Hindustan Aeronautics Limited will make in India advanced fighter jet engines for the country's indigenous light combat aircraft. This means a "greater transfer of US jet engine technology than ever before" - a clear sign that Washington not only wants to sell arms to India but is also comfortable with sharing military technology.
India will proceed with a $3bn purchase of the battle-tested MQ-9B Predator drones from General Atomics, which will also set up a facility in India. The drones will be assembled in India, which fits into Mr Modi's 'Make in India' campaign. The US supplies only 11% of India's arms - Russia is the biggest (45%) supplier - but hopes to become the primary provider in the coming years. Mr Kugelman says Washington's immediate goal is to "strengthen India's military capacity to counter China".
Mr Modi wants to make India a semiconductor base. US memory chip giant Micron Technology will invest up to $825m to build a semiconductor assembly and test facility in India, creating thousands of jobs.
US semiconductor equipment maker Lam Research will train 60,000 Indian engineers through a network of interconnected labs and research centres to speed up India's semiconductor education and workforce development. Also Applied Materials, the biggest maker of machines for producing semiconductors, will invest $400m to establish an engineering centre in India.
"It is all about the future now. Both sides are talking about cutting-edge technologies and how to seed and shape the future," says Ms Sirohi.

: U.S. President Joe Biden and first lady Jill Biden welcome India Prime Minister Narendra Modi to the White House on June 21, 2023 in Washington, DC
Mr Biden and Mrs Biden welcome Mr Modi to the White House
The India-US relationship has seen many ups and downs since the US seriously began courting India - first under President Bill Clinton and then under the George Bush administration. The response from India was measured, never overeager or too forthcoming.

The reason was the way India saw geopolitics and its own place in the global order. The strategy of nonalignment, started by India's first prime minister Jawaharlal Nehru, has always been deeply rooted into India's foreign policy.

India never wanted to be seen in one camp or the other, or to be seen as junior strategic partner to a global superpower. Mr Modi has not left the ideals of what some describe as "strategic altruism" in Indian foreign policy.

But Mr Modi is leading a different kind of India, one which has considerably more economic and geopolitical heft. He has owned the India-US relations - he formed close bonds with former presidents Barack Obama and Donald Trump and now with Mr Biden.

But India's "strategic autonomy" has not been sacrificed. Washington would have wanted India to go a step further on Russia and probably take a harder public stand on China.

But the Biden administration didn't seem disappointed as Mr Modi repeated his line that "this was not the era of war" without mentioning Russia. The Indian prime minister did speak about the importance of beefing up humanitarian assistance to Ukraine. He didn't mention China by name either but did talk about the importance of a free and prosperous Indo-Pacific.

This is how far Mr Modi could have pushed his administration's policy without compromising on strategic autonomy. It may not have been the ideal way for Washington but it didn't come in the way of making Mr Modi's visit a success.

The United States Air Force (USAF) and Indian Air Force (IAF) personnel are posing in front of a United States Air Force (USAF) F-15 Eagle fighter jet during the joint 'Exercise Cope India 2023' at the air force station in Kalaikunda, around 170 km west of Kolkata, on April 24th, 2023.
US and Indian air force personnel pose in front of a US fighter jet during a joint exercise in India in April
"The two militaries are working more closely together. They now have arrangements in place where they could use each other's facilities for refuelling and maintenance purposes. They are holding joint exercises and they're sharing a lot more intelligence. Credit to Mr Modi for managing to really test the limits of strategic autonomy. In the sense that he is getting about as close as you can to a major power without signing on to a full-fledged alliance," Mr Kugelman says.

India and the US have had major trade differences in recent years over tariffs. Trade relations particularly suffered during the Trump administration.

The two sides were not expected to announce anything major in trade as it was understood that the discussions over that could continue later without overshadowing the visit.

But surprisingly, the two sides announced that six separate trade disputes at the World Trade Organization were resolved, including one that involved tariffs.

The US is now India's top trading partner at $130bn in goods and Delhi is Washington's eighth largest partner. While these numbers are impressive, analysts and policymakers feel there is a huge untapped potential. India is also a burgeoning market with an expanding middle class and it's been positioning itself as an alternative to China to become a manufacturing hub for the world.

President Joe Biden and Indian Prime Minister Narendra Modi participate in an arrival ceremony on the South Lawn of the White House on Thursday, June 22, 2023 in Washington, DC. President Biden is the first U.S. President to invite Prime Minister Modi for an official state visit
Some 2.7 million Indians live in the US
Many global firms and nations are interested in the proposal as they look to free the global supply chain from China's dominance. In that context, the resolution of trade disputes will give further impetus to unlocking the full potential of India-US trade ties. Mr Modi has said that "even sky is not the limit (for India-US) ties".

Critics in Washington have questioned India's "democratic backsliding" under Mr Modi and his Hindu nationalist Bharatiya Janata Party (BJP). Mr Obama, in a television interview this week, emphasised the significance of addressing the "protection of the Muslim minority in a predominantly Hindu India" during discussions between Mr Biden and Mr Modi. "The progressives in the Democratic Party are disturbed by what is happening in India. The realists and centrists are all for strengthening the relationship because of the China factor," says Ms Sirohi.
'''

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [3]:
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts([text])

In [5]:
tokenizer.word_index

{'the': 1,
 'in': 2,
 'to': 3,
 'a': 4,
 'and': 5,
 'india': 6,
 'of': 7,
 'mr': 8,
 'us': 9,
 'is': 10,
 'modi': 11,
 'that': 12,
 'biden': 13,
 'has': 14,
 'as': 15,
 'with': 16,
 'not': 17,
 "india's": 18,
 'for': 19,
 'washington': 20,
 'an': 21,
 'it': 22,
 'will': 23,
 'but': 24,
 'are': 25,
 'on': 26,
 'indian': 27,
 'prime': 28,
 'minister': 29,
 'this': 30,
 'says': 31,
 'have': 32,
 'trade': 33,
 'visit': 34,
 'by': 35,
 'president': 36,
 'been': 37,
 'about': 38,
 'relationship': 39,
 'more': 40,
 'up': 41,
 'during': 42,
 'also': 43,
 'china': 44,
 'strategic': 45,
 'air': 46,
 'force': 47,
 'state': 48,
 'his': 49,
 'ties': 50,
 'two': 51,
 'at': 52,
 'white': 53,
 'house': 54,
 'be': 55,
 'lot': 56,
 'make': 57,
 'sirohi': 58,
 'technology': 59,
 'jet': 60,
 'semiconductor': 61,
 'now': 62,
 'first': 63,
 'was': 64,
 'global': 65,
 'he': 66,
 'without': 67,
 'they': 68,
 'narendra': 69,
 'joe': 70,
 'world': 71,
 'potential': 72,
 'how': 73,
 'become': 74,
 'kugelman': 75

In [6]:
len(tokenizer.word_index)

586

In [8]:
input_sentence = []
for sentences in text.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentences])[0]

  for i in range(1, len(tokenized_sentence)):
    input_sentence.append(tokenized_sentence[: i+1])
     #(1,3)

In [34]:
input_sentence

[[98, 4],
 [98, 4, 174],
 [98, 4, 174, 48],
 [98, 4, 174, 48, 34],
 [98, 4, 174, 48, 34, 35],
 [98, 4, 174, 48, 34, 35, 27],
 [98, 4, 174, 48, 34, 35, 27, 28],
 [98, 4, 174, 48, 34, 35, 27, 28, 29],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11, 3],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11, 3, 20],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11, 3, 20, 9],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11, 3, 20, 9, 36],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11, 3, 20, 9, 36, 70],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11, 3, 20, 9, 36, 70, 13],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11, 3, 20, 9, 36, 70, 13, 14],
 [98, 4, 174, 48, 34, 35, 27, 28, 29, 69, 11, 3, 20, 9, 36, 70, 13, 14, 175],
 [98,
  4,
  174,
  48,
  34,
  35,
  27,
  28,
  29,
  69,
  11,
  3,
  20,
  9,
  36,
  70,
  13,
  14,
  175,
  49],
 [98,
  4,
  174,
  48,
  34,
  35,
  27,
  28,
  29,
  69,
  11,
  3,
  20,
  9,
  

In [10]:
max_len = max([len(x) for x in input_sentence])
max_len

83

In [11]:
from keras.utils import pad_sequences

padded_sequences = pad_sequences(input_sentence, padding = 'pre', maxlen = max_len)
padded_sequences

array([[  0,   0,   0, ...,   0,  98,   4],
       [  0,   0,   0, ...,  98,   4, 174],
       [  0,   0,   0, ...,   4, 174,  48],
       ...,
       [  0,   0, 564, ...,  44, 586,  31],
       [  0, 564,   2, ..., 586,  31,  77],
       [564,   2,  20, ...,  31,  77,  58]], dtype=int32)

In [13]:
padded_sequences[:3]

#post padding will have diff indexes
# we are using pre as a padding method since we can use X for everything and Y as the last output
# 0-93 - X and Y - 1
# 0-1 - X and Y - 13

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  98,   4],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  98,   4, 174],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0

In [16]:
padded_sequences[:, :-1]  #[rows, columns]

array([[  0,   0,   0, ...,   0,   0,  98],
       [  0,   0,   0, ...,   0,  98,   4],
       [  0,   0,   0, ...,  98,   4, 174],
       ...,
       [  0,   0, 564, ...,   1,  44, 586],
       [  0, 564,   2, ...,  44, 586,  31],
       [564,   2,  20, ..., 586,  31,  77]], dtype=int32)

In [17]:
padded_sequences[:, -1]

array([  4, 174,  48, ...,  31,  77,  58], dtype=int32)

In [43]:
X = padded_sequences[:, :-1]
y = padded_sequences[:, -1]

In [44]:
 X[2]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,  98,   4, 174], dtype=int32)

In [20]:
y[2]

48

In [21]:
X.shape

(1333, 82)

We need to convert output in one hot encoded version - To convert it in multi-class classification. For eg. 2nd word = [0,1,0]

In [22]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes = len(tokenizer.word_index)+1)  #distinct words -

In [23]:
y[2]  #1st word  #starts with 0    #y[2] --> 7

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [24]:
X.shape

(1333, 82)

In [25]:
y.shape

(1333, 587)

In [26]:
len(tokenizer.word_index)

586

In [27]:
tokenizer.word_index

{'the': 1,
 'in': 2,
 'to': 3,
 'a': 4,
 'and': 5,
 'india': 6,
 'of': 7,
 'mr': 8,
 'us': 9,
 'is': 10,
 'modi': 11,
 'that': 12,
 'biden': 13,
 'has': 14,
 'as': 15,
 'with': 16,
 'not': 17,
 "india's": 18,
 'for': 19,
 'washington': 20,
 'an': 21,
 'it': 22,
 'will': 23,
 'but': 24,
 'are': 25,
 'on': 26,
 'indian': 27,
 'prime': 28,
 'minister': 29,
 'this': 30,
 'says': 31,
 'have': 32,
 'trade': 33,
 'visit': 34,
 'by': 35,
 'president': 36,
 'been': 37,
 'about': 38,
 'relationship': 39,
 'more': 40,
 'up': 41,
 'during': 42,
 'also': 43,
 'china': 44,
 'strategic': 45,
 'air': 46,
 'force': 47,
 'state': 48,
 'his': 49,
 'ties': 50,
 'two': 51,
 'at': 52,
 'white': 53,
 'house': 54,
 'be': 55,
 'lot': 56,
 'make': 57,
 'sirohi': 58,
 'technology': 59,
 'jet': 60,
 'semiconductor': 61,
 'now': 62,
 'first': 63,
 'was': 64,
 'global': 65,
 'he': 66,
 'without': 67,
 'they': 68,
 'narendra': 69,
 'joe': 70,
 'world': 71,
 'potential': 72,
 'how': 73,
 'become': 74,
 'kugelman': 75

LSTM Architecture

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding

model = Sequential()
model.add(Embedding(587, 100, input_length = 82))
model.add(LSTM(150))
model.add(Dense(587, activation = 'softmax'))

In [40]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [41]:
# model.summary()

In [42]:
model.fit(X, y, epochs = 50)

Epoch 1/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 10s 169ms/step - accuracy: 0.0379 - loss: 6.2657
Epoch 2/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 10s 170ms/step - accuracy: 0.0450 - loss: 5.7501
Epoch 3/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 9s 145ms/step - accuracy: 0.0554 - loss: 5.6863
Epoch 4/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 10s 135ms/step - accuracy: 0.0578 - loss: 5.6771
Epoch 5/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 10s 134ms/step - accuracy: 0.0597 - loss: 5.5673
Epoch 6/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 7s 161ms/step - accuracy: 0.0526 - loss: 5.4129
Epoch 7/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 6s 140ms/step - accuracy: 0.0620 - loss: 5.3049
Epoch 8/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 7s 161ms/step - accuracy: 0.0852 - loss: 5.0614
Epoch 9/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 9s 136ms/step - accuracy: 0.1145 - loss: 4.8404
Epoch 10/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 10s 135ms/step - accuracy: 0.1072 - loss: 4.6662
Epoch 11/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 10s 137ms/step - accuracy: 0.1294 - loss: 4.4256
Epoch 12/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 11s 153

In [45]:
text = 'Narendra Modi'

#tokenize
tokenized_word = tokenizer.texts_to_sequences([text])[0]

#padding

padded_word = pad_sequences([tokenized_word], maxlen = 56, padding = 'pre')

#prediction

prediction_index = np.argmax(model.predict(padded_word))  #112th index

for word, index in tokenizer.word_index.items():
  if index == prediction_index:
    text = text + ' ' + word
    print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step
Narendra Modi wants


In [46]:
import time
text = 'Narendra Modi'

for i in range(10):   #predict until 10th word
  #tokenize
  tokenized_word = tokenizer.texts_to_sequences([text])[0]

  #padding

  padded_word = pad_sequences([tokenized_word], maxlen = 56, padding = 'pre')

  #prediction

  prediction_index = np.argmax(model.predict(padded_word))  #112th index

  for word, index in tokenizer.word_index.items():
    if index == prediction_index:
      text = text + ' '+ word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
Narendra Modi wants
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
Narendra Modi wants to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
Narendra Modi wants to make
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
Narendra Modi wants to make india
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
Narendra Modi wants to make india a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
Narendra Modi wants to make india a semiconductor
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Narendra Modi wants to make india a semiconductor base
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
Narendra Modi wants to make india a semiconductor base us
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
Narendra Modi wants to make india a semiconductor base us memory
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Narendra Modi wants to make india a semiconductor base us memory chip


In [47]:
tokenizer.word_index

{'the': 1,
 'in': 2,
 'to': 3,
 'a': 4,
 'and': 5,
 'india': 6,
 'of': 7,
 'mr': 8,
 'us': 9,
 'is': 10,
 'modi': 11,
 'that': 12,
 'biden': 13,
 'has': 14,
 'as': 15,
 'with': 16,
 'not': 17,
 "india's": 18,
 'for': 19,
 'washington': 20,
 'an': 21,
 'it': 22,
 'will': 23,
 'but': 24,
 'are': 25,
 'on': 26,
 'indian': 27,
 'prime': 28,
 'minister': 29,
 'this': 30,
 'says': 31,
 'have': 32,
 'trade': 33,
 'visit': 34,
 'by': 35,
 'president': 36,
 'been': 37,
 'about': 38,
 'relationship': 39,
 'more': 40,
 'up': 41,
 'during': 42,
 'also': 43,
 'china': 44,
 'strategic': 45,
 'air': 46,
 'force': 47,
 'state': 48,
 'his': 49,
 'ties': 50,
 'two': 51,
 'at': 52,
 'white': 53,
 'house': 54,
 'be': 55,
 'lot': 56,
 'make': 57,
 'sirohi': 58,
 'technology': 59,
 'jet': 60,
 'semiconductor': 61,
 'now': 62,
 'first': 63,
 'was': 64,
 'global': 65,
 'he': 66,
 'without': 67,
 'they': 68,
 'narendra': 69,
 'joe': 70,
 'world': 71,
 'potential': 72,
 'how': 73,
 'become': 74,
 'kugelman': 75

In [141]:
tokenizer.word_index.items()

dict_items([('the', 1), ('you', 2), ('i', 3), ('to', 4), ('a', 5), ('of', 6), ('is', 7), ('have', 8), ('will', 9), ('can', 10), ('what', 11), ('course', 12), ('program', 13), ('in', 14), ('for', 15), ('all', 16), ('sessions', 17), ('on', 18), ('be', 19), ('and', 20), ('this', 21), ('if', 22), ('am', 23), ('pay', 24), ('payment', 25), ('make', 26), ('we', 27), ('do', 28), ('subscription', 29), ('where', 30), ('rs', 31), ('so', 32), ('campusx', 33), ('session', 34), ('our', 35), ('paid', 36), ('join', 37), ('able', 38), ('your', 39), ('website', 40), ('placement', 41), ('fee', 42), ('data', 43), ('monthly', 44), ('month', 45), ('not', 46), ('get', 47), ('yes', 48), ('once', 49), ('past', 50), ('feb', 51), ('assistance', 52), ('science', 53), ('7', 54), ('5600', 55), ('are', 56), ('watch', 57), ('google', 58), ('by', 59), ('com', 60), ('mail', 61), ('from', 62), ('contact', 63), ('us', 64), ('at', 65), ('or', 66), ('doubt', 67), ('mentorship', 68), ('payments', 69), ('799', 70), ('total',